export const SAVE_CHECKIN_DATE = "SAVE_CHECKIN_DATE";
export const SAVE_CHECKOUT_DATE = "SAVE_CHECKOUT_DATE";
export const SAVE_ROOM_TYPE = "SAVE_ROOM_TYPE";
export const SAVE_VIEW_SELECTION = "SAVE_VIEW_SELECTION";
export const SAVE_CARD_INFORMATIONS = "SAVE_CARD_INFORMATIONS";
